-- 마음잇다 백엔드 초기 스키마 (MySQL 8.0 이상)
-- 테이블명세서_마음잇다.hwp 기준
-- 날짜/시간은 UTC로 저장하고, REPORT_DATE/START_DATE만 Asia/Seoul 기준 업무 날짜로 계산한다.
SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT NOT NULL,
    LOGIN_ID VARCHAR(50) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    ROLE ENUM('SENIOR', 'GUARDIAN') NOT NULL,
    NOTIFICATION_ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    EMOTION_ALERT_THRESHOLD TINYINT UNSIGNED NULL,
    CHECKIN_REMINDER_TIME TIME NULL,
    JOINED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    WITHDRAWN_AT DATETIME NULL,
    PRIMARY KEY (USER_ID),
    CONSTRAINT UK_USERS_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT CK_USERS_WITHDRAWN_AT CHECK (
        WITHDRAWN_AT IS NULL OR WITHDRAWN_AT >= JOINED_AT
    ),
    CONSTRAINT CK_USERS_EMOTION_ALERT_THRESHOLD CHECK (
        EMOTION_ALERT_THRESHOLD IS NULL
        OR EMOTION_ALERT_THRESHOLD BETWEEN 0 AND 100
    )
);

CREATE TABLE GUARDIAN_SENIOR_RELATIONSHIP (
    RELATIONSHIP_ID INT AUTO_INCREMENT NOT NULL,
    GUARDIAN_ID INT NOT NULL,
    SENIOR_ID INT NOT NULL,
    CONNECTION_STATUS ENUM(
        'REQUESTED',
        'CONNECTED',
        'REJECTED',
        'DISCONNECTED'
    ) NOT NULL DEFAULT 'REQUESTED',
    REQUESTED_AT DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    APPROVED_AT DATETIME(3) NULL,
    DISCONNECTED_AT DATETIME(3) NULL,
    ACTIVE_GUARDIAN_ID INT GENERATED ALWAYS AS (
        CASE
            WHEN CONNECTION_STATUS IN ('REQUESTED', 'CONNECTED')
            THEN GUARDIAN_ID
            ELSE NULL
        END
    ) STORED,
    ACTIVE_SENIOR_ID INT GENERATED ALWAYS AS (
        CASE
            WHEN CONNECTION_STATUS IN ('REQUESTED', 'CONNECTED')
            THEN SENIOR_ID
            ELSE NULL
        END
    ) STORED,
    PRIMARY KEY (RELATIONSHIP_ID),
    CONSTRAINT UK_RELATIONSHIP_ACTIVE_GUARDIAN UNIQUE (ACTIVE_GUARDIAN_ID),
    CONSTRAINT UK_RELATIONSHIP_ACTIVE_SENIOR UNIQUE (ACTIVE_SENIOR_ID),
    CONSTRAINT FK_RELATIONSHIP_GUARDIAN
        FOREIGN KEY (GUARDIAN_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT FK_RELATIONSHIP_SENIOR
        FOREIGN KEY (SENIOR_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT CK_RELATIONSHIP_DIFFERENT_USERS CHECK (
        GUARDIAN_ID <> SENIOR_ID
    ),
    CONSTRAINT CK_RELATIONSHIP_STATUS_TIME CHECK (
        (
            CONNECTION_STATUS IN ('REQUESTED', 'REJECTED')
            AND APPROVED_AT IS NULL
            AND DISCONNECTED_AT IS NULL
        )
        OR
        (
            CONNECTION_STATUS = 'CONNECTED'
            AND APPROVED_AT IS NOT NULL
            AND DISCONNECTED_AT IS NULL
        )
        OR
        (
            CONNECTION_STATUS = 'DISCONNECTED'
            AND APPROVED_AT IS NOT NULL
            AND DISCONNECTED_AT IS NOT NULL
        )
    ),
    CONSTRAINT CK_RELATIONSHIP_TIME_ORDER CHECK (
        (APPROVED_AT IS NULL OR REQUESTED_AT <= APPROVED_AT)
        AND
        (DISCONNECTED_AT IS NULL OR APPROVED_AT <= DISCONNECTED_AT)
    ),
    INDEX IX_RELATIONSHIP_GUARDIAN_HISTORY (
        GUARDIAN_ID,
        REQUESTED_AT,
        RELATIONSHIP_ID
    ),
    INDEX IX_RELATIONSHIP_SENIOR_HISTORY (
        SENIOR_ID,
        REQUESTED_AT,
        RELATIONSHIP_ID
    )
);

CREATE TABLE CONVERSATION_MESSAGE (
    MESSAGE_ID INT AUTO_INCREMENT NOT NULL,
    SENIOR_ID INT NOT NULL,
    SPEAKER_TYPE ENUM('AI', 'SENIOR') NOT NULL,
    CONTENT TEXT NULL,
    CREATED_AT DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    STT_STATUS ENUM(
        'NOT_REQUIRED',
        'WAITING',
        'PROCESSING',
        'COMPLETED',
        'FAILED'
    ) NOT NULL DEFAULT 'NOT_REQUIRED',
    STT_ERROR_MESSAGE TEXT NULL,
    PRIMARY KEY (MESSAGE_ID),
    CONSTRAINT FK_MESSAGE_SENIOR
        FOREIGN KEY (SENIOR_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT CK_MESSAGE_SPEAKER_STT CHECK (
        SPEAKER_TYPE = 'SENIOR' OR STT_STATUS = 'NOT_REQUIRED'
    ),
    CONSTRAINT CK_MESSAGE_CONTENT CHECK (
        CONTENT IS NOT NULL
        OR
        (
            SPEAKER_TYPE = 'SENIOR'
            AND STT_STATUS IN ('WAITING', 'PROCESSING', 'FAILED')
        )
    ),
    CONSTRAINT CK_MESSAGE_STT_ERROR CHECK (
        (
            STT_STATUS = 'FAILED'
            AND STT_ERROR_MESSAGE IS NOT NULL
        )
        OR
        (
            STT_STATUS <> 'FAILED'
            AND STT_ERROR_MESSAGE IS NULL
        )
    ),
    INDEX IX_MESSAGE_SENIOR_CREATED (
        SENIOR_ID,
        CREATED_AT,
        MESSAGE_ID
    )
);

CREATE TABLE MESSAGE_RELATIONSHIP (
    RELATIONSHIP_ID INT AUTO_INCREMENT NOT NULL,
    SOURCE_MESSAGE_ID INT NOT NULL,
    TARGET_MESSAGE_ID INT NOT NULL,
    RELATIONSHIP_TYPE ENUM('ANSWER', 'ADDITIONAL_ANSWER') NOT NULL,
    PRIMARY KEY (RELATIONSHIP_ID),
    CONSTRAINT FK_RELATIONSHIP_SOURCE_MESSAGE
        FOREIGN KEY (SOURCE_MESSAGE_ID)
        REFERENCES CONVERSATION_MESSAGE (MESSAGE_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_RELATIONSHIP_TARGET_MESSAGE
        FOREIGN KEY (TARGET_MESSAGE_ID)
        REFERENCES CONVERSATION_MESSAGE (MESSAGE_ID)
        ON DELETE CASCADE,
    CONSTRAINT UK_MESSAGE_RELATIONSHIP UNIQUE (
        SOURCE_MESSAGE_ID,
        TARGET_MESSAGE_ID,
        RELATIONSHIP_TYPE
    ),
    CONSTRAINT CK_RELATIONSHIP_DIFFERENT_MESSAGES CHECK (
        SOURCE_MESSAGE_ID <> TARGET_MESSAGE_ID
    ),
    INDEX IX_RELATIONSHIP_TARGET_MESSAGE (TARGET_MESSAGE_ID)
);

CREATE TABLE SCALE_QUESTION_ANALYSIS (
    SCALE_ANALYSIS_ID INT AUTO_INCREMENT NOT NULL,
    MESSAGE_ID INT NOT NULL,
    SCALE_TYPE ENUM('SGDS_K', 'GAD_7', 'LSNS_6') NOT NULL,
    QUESTION_NUMBER INT NOT NULL,
    ANALYSIS_SCORE INT NOT NULL,
    ANALYZED_AT DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (SCALE_ANALYSIS_ID),
    CONSTRAINT FK_SCALE_ANALYSIS_MESSAGE
        FOREIGN KEY (MESSAGE_ID)
        REFERENCES CONVERSATION_MESSAGE (MESSAGE_ID)
        ON DELETE CASCADE,
    CONSTRAINT UK_SCALE_MESSAGE_QUESTION UNIQUE (
        MESSAGE_ID,
        SCALE_TYPE,
        QUESTION_NUMBER
    ),
    CONSTRAINT CK_SCALE_ANALYSIS_SCORE CHECK (
        ANALYSIS_SCORE IN (0, 1)
    ),
    CONSTRAINT CK_SCALE_QUESTION_NUMBER CHECK (
        (SCALE_TYPE = 'SGDS_K' AND QUESTION_NUMBER BETWEEN 1 AND 15)
        OR
        (SCALE_TYPE = 'GAD_7' AND QUESTION_NUMBER BETWEEN 1 AND 7)
        OR
        (SCALE_TYPE = 'LSNS_6' AND QUESTION_NUMBER BETWEEN 1 AND 6)
    )
);

CREATE TABLE EMOTION_TAG (
    EMOTION_TAG_ID INT AUTO_INCREMENT NOT NULL,
    MESSAGE_ID INT NOT NULL,
    SENTIMENT_LABEL ENUM('POSITIVE', 'NEUTRAL', 'NEGATIVE') NOT NULL,
    ANALYZED_AT DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (EMOTION_TAG_ID),
    CONSTRAINT UK_EMOTION_TAG_MESSAGE UNIQUE (MESSAGE_ID),
    CONSTRAINT FK_EMOTION_TAG_MESSAGE
        FOREIGN KEY (MESSAGE_ID)
        REFERENCES CONVERSATION_MESSAGE (MESSAGE_ID)
        ON DELETE CASCADE
);

CREATE TABLE VOICE_ANALYSIS_STATUS (
    VOICE_ANALYSIS_ID INT AUTO_INCREMENT NOT NULL,
    MESSAGE_ID INT NOT NULL,
    PROCESSING_STATUS ENUM(
        'WAITING',
        'PROCESSING',
        'COMPLETED',
        'FAILED'
    ) NOT NULL DEFAULT 'WAITING',
    ANALYZED_AT DATETIME(3) NULL,
    ERROR_MESSAGE TEXT NULL,
    PRIMARY KEY (VOICE_ANALYSIS_ID),
    CONSTRAINT UK_VOICE_ANALYSIS_MESSAGE UNIQUE (MESSAGE_ID),
    CONSTRAINT FK_VOICE_ANALYSIS_MESSAGE
        FOREIGN KEY (MESSAGE_ID)
        REFERENCES CONVERSATION_MESSAGE (MESSAGE_ID)
        ON DELETE CASCADE,
    CONSTRAINT CK_VOICE_ANALYSIS_RESULT CHECK (
        (
            PROCESSING_STATUS IN ('WAITING', 'PROCESSING')
            AND ANALYZED_AT IS NULL
            AND ERROR_MESSAGE IS NULL
        )
        OR
        (
            PROCESSING_STATUS = 'COMPLETED'
            AND ANALYZED_AT IS NOT NULL
            AND ERROR_MESSAGE IS NULL
        )
        OR
        (
            PROCESSING_STATUS = 'FAILED'
            AND ERROR_MESSAGE IS NOT NULL
        )
    )
);

CREATE TABLE WEEKLY_EMOTION_REPORT (
    WEEKLY_REPORT_ID INT AUTO_INCREMENT NOT NULL,
    SENIOR_ID INT NOT NULL,
    START_DATE DATE NOT NULL,
    WEEKLY_SUMMARY TEXT NOT NULL,
    GENERATION_STATUS ENUM(
        'WAITING',
        'COMPLETED',
        'FAILED'
    ) NOT NULL DEFAULT 'WAITING',
    CREATED_AT DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UPDATED_AT DATETIME(3)
        NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
        ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (WEEKLY_REPORT_ID),
    CONSTRAINT FK_WEEKLY_REPORT_SENIOR
        FOREIGN KEY (SENIOR_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT UK_WEEKLY_REPORT_SENIOR_START UNIQUE (
        SENIOR_ID,
        START_DATE
    )
);

CREATE TABLE DAILY_EMOTION_REPORT (
    REPORT_ID INT AUTO_INCREMENT NOT NULL,
    WEEKLY_REPORT_ID INT NULL,
    SENIOR_ID INT NOT NULL,
    REPORT_DATE DATE NOT NULL,
    EMOTION_INDEX INT NULL,
    ONE_LINE_SUMMARY VARCHAR(500) NULL,
    RECOMMENDED_ACTION TEXT NULL,
    GENERATION_STATUS ENUM(
        'WAITING',
        'COMPLETED',
        'FAILED'
    ) NOT NULL DEFAULT 'WAITING',
    CREATED_AT DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (REPORT_ID),
    CONSTRAINT FK_DAILY_REPORT_WEEKLY
        FOREIGN KEY (WEEKLY_REPORT_ID)
        REFERENCES WEEKLY_EMOTION_REPORT (WEEKLY_REPORT_ID)
        ON DELETE SET NULL,
    CONSTRAINT FK_DAILY_REPORT_SENIOR
        FOREIGN KEY (SENIOR_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT UK_DAILY_REPORT_SENIOR_DATE UNIQUE (
        SENIOR_ID,
        REPORT_DATE
    ),
    CONSTRAINT CK_DAILY_REPORT_EMOTION_INDEX CHECK (
        EMOTION_INDEX IS NULL OR EMOTION_INDEX BETWEEN 0 AND 100
    ),
    INDEX IX_DAILY_REPORT_WEEKLY (WEEKLY_REPORT_ID)
);

CREATE TABLE DAILY_REPORT_EVIDENCE (
    REPORT_ID INT NOT NULL,
    MESSAGE_ID INT NOT NULL,
    PRIMARY KEY (REPORT_ID, MESSAGE_ID),
    CONSTRAINT FK_EVIDENCE_REPORT
        FOREIGN KEY (REPORT_ID)
        REFERENCES DAILY_EMOTION_REPORT (REPORT_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_EVIDENCE_MESSAGE
        FOREIGN KEY (MESSAGE_ID)
        REFERENCES CONVERSATION_MESSAGE (MESSAGE_ID)
        ON DELETE CASCADE,
    INDEX IX_DAILY_EVIDENCE_MESSAGE (MESSAGE_ID)
);

CREATE TABLE GUARDIAN_NOTIFICATION (
    ALERT_ID INT AUTO_INCREMENT NOT NULL,
    GUARDIAN_ID INT NOT NULL,
    DAILY_REPORT_ID INT NULL,
    WEEKLY_REPORT_ID INT NULL,
    ALERT_TYPE ENUM(
        'EMOTION_INDEX_DROP',
        'WEEKLY_REPORT_READY'
    ) NOT NULL,
    CONTENT TEXT NOT NULL,
    IS_READ BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (ALERT_ID),
    CONSTRAINT FK_NOTIFICATION_GUARDIAN
        FOREIGN KEY (GUARDIAN_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT FK_NOTIFICATION_DAILY_REPORT
        FOREIGN KEY (DAILY_REPORT_ID)
        REFERENCES DAILY_EMOTION_REPORT (REPORT_ID),
    CONSTRAINT FK_NOTIFICATION_WEEKLY_REPORT
        FOREIGN KEY (WEEKLY_REPORT_ID)
        REFERENCES WEEKLY_EMOTION_REPORT (WEEKLY_REPORT_ID),
    CONSTRAINT UK_NOTIFICATION_DAILY_REPORT UNIQUE (DAILY_REPORT_ID),
    CONSTRAINT UK_NOTIFICATION_WEEKLY_REPORT UNIQUE (WEEKLY_REPORT_ID),
    CONSTRAINT CK_NOTIFICATION_TARGET CHECK (
        (
            ALERT_TYPE = 'EMOTION_INDEX_DROP'
            AND DAILY_REPORT_ID IS NOT NULL
            AND WEEKLY_REPORT_ID IS NULL
        )
        OR
        (
            ALERT_TYPE = 'WEEKLY_REPORT_READY'
            AND DAILY_REPORT_ID IS NULL
            AND WEEKLY_REPORT_ID IS NOT NULL
        )
    ),
    INDEX IX_NOTIFICATION_GUARDIAN_LIST (
        GUARDIAN_ID,
        IS_READ,
        CREATED_AT,
        ALERT_ID
    )
);

SHOW TABLES;
